spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/filestorage}
    username: ${SPRING_DATASOURCE_USERNAME:fs_user}
    password: ${SPRING_DATASOURCE_PASSWORD:fs_pass}
  jpa:
    hibernate:
      ddl-auto: update

storage:
  base-path: ${STORAGE_BASE_PATH:/tmp/files}

server:
  port: ${STORAGE_SERVER_PORT:8081}
