services:
  gateway:
    build: gateway
    environment:
      - STORAGE_SERVICE_BASE_URL=http://storage:8080
      - ANALYSIS_SERVICE_BASE_URL=http://analysis:8080
    ports:
      - "8080:8080"
    depends_on:
      - filestorage
#      - analysis
    networks:
      - app-net

  filestorage:
    build: ./filestorage
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://filestorage-db:5432/filestore
      - SPRING_DATASOURCE_USERNAME=fs_user
      - SPRING_DATASOURCE_PASSWORD=fs_pass
      - STORAGE_BASE_PATH=/data/storage
      - STORAGE_SERVER_PORT=8081
    volumes:
      - filestorage-data:/data/storage
    depends_on:
      filestorage-db:
        condition: service_healthy
    networks:
      - app-net


  filestorage-db:
    image: postgres:15
    environment:
      POSTGRES_DB: filestorage
      POSTGRES_USER: fs_user
      POSTGRES_PASSWORD: fs_pass
    volumes:
      - fs_pg_data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fs_user -d filestorage" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  fs_pg_data:
  filestorage-data:

networks:
  app-net: