services:
  gateway:
    build: gateway
    environment:
      - STORAGE_SERVICE_BASE_URL=http://filestorage:8080
      - ANALYSIS_SERVICE_BASE_URL=http://analysis:8080
    ports:
      - "8080:8080"
    depends_on:
      - filestorage
      - analysis
    networks:
      - app-net

  filestorage:
    build: ./filestorage
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://filestorage-db:5432/filestorage
      - SPRING_DATASOURCE_USERNAME=fs_user
      - SPRING_DATASOURCE_PASSWORD=fs_pass
      - STORAGE_BASE_PATH=/data/storage
      - STORAGE_SERVER_PORT=8080
    volumes:
      - filestorage-data:/data/storage
    depends_on:
      filestorage-db:
        condition: service_healthy
    networks:
      - app-net


  filestorage-db:
    image: postgres:15
    environment:
      POSTGRES_DB: filestorage
      POSTGRES_USER: fs_user
      POSTGRES_PASSWORD: fs_pass
    volumes:
      - fs_pg_data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fs_user -d filestorage" ]
      interval: 5s
      timeout: 5s
      retries: 5


  analysis:
    build: ./analysis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://analysis-db:5432/analyses
      - SPRING_DATASOURCE_USERNAME=an_user
      - SPRING_DATASOURCE_PASSWORD=an_pass
      - ANALYSIS_IMAGE_PATH=/data/storage
      - FILESTORAGE_SERVICE_URL=http://filestorage:8080
      - ANALYSIS_SERVER_PORT=8080
    volumes:
      - analysis-data:/data/storage
    depends_on:
      analysis-db:
        condition: service_healthy
    networks:
      - app-net


  analysis-db:
    image: postgres:15
    environment:
      POSTGRES_DB: analyses
      POSTGRES_USER: an_user
      POSTGRES_PASSWORD: an_pass
    volumes:
      - an_pg_data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U an_user -d analyses" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  fs_pg_data:
  an_pg_data:
  filestorage-data:
  analysis-data:

networks:
  app-net: