spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${SPRING_DATASOURCE_USERNAME:pay_user}
    password: ${SPRING_DATASOURCE_PASSWORD:pay_pass}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

server:
  port: ${PAYMENTS_SERVER_PORT:8081}

app:
  queues:
    payment-requests: q.payment.requests
    payment-outcomes: q.payment.outcomes
